// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Audio: typeof import('./src/components/Audio.vue')['default']
    BannerThree: typeof import('./src/components/Banner/BannerThree.vue')['default']
    BannerTwo: typeof import('./src/components/Banner/BannerTwo.vue')['default']
    Col: typeof import('./src/components/Col.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Navs: typeof import('./src/components/Navs.vue')['default']
    OptionBtn: typeof import('./src/components/OptionBtn.vue')['default']
    PlayController: typeof import('./src/components/PlayController.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/Row.vue')['default']
    Scroll: typeof import('./src/components/Scroll.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Slider: typeof import('./src/components/slider/Slider.vue')['default']
    SongCard: typeof import('./src/components/SongCard.vue')['default']
    SongPanel: typeof import('./src/components/SongPanel.vue')['default']
    SongSearch: typeof import('./src/components/SongSearch.vue')['default']
    Sticky: typeof import('./src/components/Sticky.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
